### ISSUE TITLE
Outbound push failing on chis-training.health.go.ke - server responsed with 400

### ISSUE THREAD

**Issue by mrjones-plip** [moh-kenya/echis-2.0-integration#130]
Outbound push has been failing since 11th of October:

![image](https://github.com/moh-kenya/echis-2.0-integration/assets/8253488/0b2f41b9-dce6-4d81-baea-18db53b42589)

It appears it's because of this error:

```
2023-10-25T04:05:09.057 ERROR: Failed to push cbbc8084-f15e-4a75-bbe9-ea77a4627ead to process_in_client_registry, server responsed with 400
2023-10-25T04:05:09.057 ERROR: Response body: {"error":"could not complete creating client {\"instance\":\"https://chis-training.health.go.ke/\",\"user\":\"cbbc8084-f15e-4a75-bbe9-ea77a4627ead\",\"error\":{\"nextOfKins[0].Residence\":[\"'Residence' must not be empty.\"]}})"}
2023-10-25T04:05:09.058 WARN: Unable to push cbbc8084-f15e-4a75-bbe9-ea77a4627ead for process_in_client_registry: StatusCodeError: 400 - {"error":"could not complete creating client {\"instance\":\"https://chis-training.health.go.ke/\",\"user\":\"cbbc8084-f15e-4a75-bbe9-ea77a4627ead\",\"error\":{\"nextOfKins[0].Residence\":[\"'Residence' must not be empty.\"]}})"}
at new StatusCodeError (/service/sentinel/node_modules/request-promise-core/lib/errors.js:32:15)
at Request.plumbing.callback (/service/sentinel/node_modules/request-promise-core/lib/plumbing.js:104:33)
at Request.RP$callback [as _callback] (/service/sentinel/node_modules/request-promise-core/lib/plumbing.js:46:31)
at Request.self.callback (/service/sentinel/node_modules/request/request.js:185:22)
at Request.emit (node:events:513:28)
at Request.<anonymous> (/service/sentinel/node_modules/request/request.js:1154:10)
at Request.emit (node:events:513:28)
at IncomingMessage.<anonymous> (/service/sentinel/node_modules/request/request.js:1076:12)
at Object.onceWrapper (node:events:627:28)
at IncomingMessage.emit (node:events:525:35) {
name: 'StatusCodeError',
statusCode: 400,
message: `400 - {"error":"could not complete creating client {\\"instance\\":\\"https://chis-training.health.go.ke/\\",\\"user\\":\\"cbbc8084-f15e-4a75-bbe9-ea77a4627ead\\",\\"error\\":{\\"nextOfKins[0].Residence\\":[\\"'Residence' must not be empty.\\"]}})"}`,
error: {
error: `could not complete creating client {"instance":"https://chis-training.health.go.ke/","user":"cbbc8084-f15e-4a75-bbe9-ea77a4627ead","error":{"nextOfKins[0].Residence":["'Residence' must not be empty."]}})`
},
[stack]: `StatusCodeError: 400 - {"error":"could not complete creating client {\\"instance\\":\\"https://chis-training.health.go.ke/\\",\\"user\\":\\"cbbc8084-f15e-4a75-bbe9-ea77a4627ead\\",\\"error\\":{\\"nextOfKins[0].Residence\\":[\\"'Residence' must not be empty.\\"]}})"}\n` +
'    at new StatusCodeError (/service/sentinel/node_modules/request-promise-core/lib/errors.js:32:15)\n' +
'    at Request.plumbing.callback (/service/sentinel/node_modules/request-promise-core/lib/plumbing.js:104:33)\n' +
'    at Request.RP$callback [as _callback] (/service/sentinel/node_modules/request-promise-core/lib/plumbing.js:46:31)\n' +
'    at Request.self.callback (/service/sentinel/node_modules/request/request.js:185:22)\n' +
'    at Request.emit (node:events:513:28)\n' +
'    at Request.<anonymous> (/service/sentinel/node_modules/request/request.js:1154:10)\n' +
'    at Request.emit (node:events:513:28)\n' +
'    at IncomingMessage.<anonymous> (/service/sentinel/node_modules/request/request.js:1076:12)\n' +
'    at Object.onceWrapper (node:events:627:28)\n' +
'    at IncomingMessage.emit (node:events:525:35)'
}
```

**Comment by derickl** [comment]
Was any progress made in the investigation @alexosugo ?
